class Textos {
  String intoleranciaALactose =
      'Não coma: leite de vaca, queijos, manteiga, requeijão e demais derivados de leite; preparações à base de leite (bolos, pudins, cremes, entre outros); bolachas e biscoitos que possuem leite em sua composição.';
  String diabetes =
      'Pacientes com história familiar de DM devem ser orientados a: manter o peso normal; não fumar; controlar a pressão arterial; evitar medicamentos que potencialmente possam agredir o pâncreas; praticar atividade física regular. Pacientes com DM devem ser orientados a: realizar exame diário dos pés para evitar o aparecimento de lesões; manter uma alimentação saudável; utilizar os medicamentos prescritos; praticar atividades físicas; manter um bom controle da glicemia, seguindo corretamente as orientações médicas.';
  String pedraNaVesicula =
      'Faça uma dieta rica em fibras e com pouca gordura. Alimentos gordurosos podem elevar o nível do colesterol; Procure manter o peso ideal para seu tipo físico. Isso ajuda a controlar o nível do colesterol e a prevenir diabetes e hipertensão; Largue o cigarro; Se você tem histórico familiar de cálculo na vesícula, discuta com seu médico a conveniência de tomar pílulas anticoncepcionais ou fazer reposição hormonal.';

  String refluxo =
      ' Não se automedique se tiver episódios repetidos de azia ou queimação. Procure assistência médica para diagnóstico e tratamento adequados; evite alimentos e bebidas, especialmente as alcoólicas, que favorecem o retorno do conteúdo gástrico;fique longe do cigarro;procure perder peso;não use cintos ou roupas apertadas na região do abdome;não se deite logo após as refeições;distribua os alimentos em pequenas quantidades por várias refeições (café da manhã, almoço, lanche da tarde e jantar);faça refeições mais leves. Sente-se e coma sem pressa, mastigando bem os alimentos;aumente a salivação com gomas de mascar ou balas duras. A saliva pode aliviar a dor;não ponha o bebê na cama assim que acabar de mamar. Mantenha-o em pé no colo até que elimine o ar que deglutiu durante a amamentação.';

  String hipertireoidismo =
      'Essa dieta deve incluir grãos integrais, proteínas magras e gorduras saldáveis. Frutas, verduras e legumes devem ser os ricos em antioxidantes, tais como morango, kiwi, ameixa vermelha, tomate, espinafre, couve e abóbora. Também é recomendada uma dieta que contenha ômega 3, presente em alguns peixes, sementes e frutos secos, que pode melhorar a função imunológica e minimizar a inflamação, e alimentos ricos em proteínas tanto animais quanto vegetais. Deve-se evitar alimentos ricos em sal, gorduras saturadas e carboidratos simples e limitar o consumo de soja e seus derivados, uma vez que estes interferem na atividade hormonal da tireoide. Recomenda-se remover completamente da dieta o álcool, o tabaco e a cafeína. Também se deve evitar alimentos refinados, como pães, massas e doces, e os que contenham gorduras saturadas e gorduras trans, como carnes vermelhas e processados. Os açúcares adicionados, como o açúcar de cana, o açúcar mascavo, o mel e os de determinados xaropes também podem agravar o hipertireoidismo.';

  String dislipidemia =
      'Alguns alimentos podem auxiliar no controle do colesterol e na prevenção de doenças cardiovasculares, procure inclui-los na sua alimentação diária: \n ​Frutas com perfil antioxidante: maçã / uva / suco de uva/ amora / frutas vermelhas / abacate; Aveia; Linhaça; Azeite de oliva; Vegetais como brócolis, berinjela, couve-flor, alcachofra; Soja / extrato de soja (leite de soja) / queijo de soja (tofu), feijões; Peixes ricos em ômega-3: salmão, atum, sardinha, anchova, bacalhau; Sementes: semente de girassol sem casca, gergelim.; Oleaginosas: castanha do Pará, amêndoas, nozes.; Chocolate amargo: rico em antioxidantes! Atenção, somente 20g por dia.';
}
